templates =  [
    "This is what I mean when I talk about {}.",
    "{} is a pretty good title for this.",
    "I found out that {} is about the following.",
    "The things most commonly associated with {} are these.",
    "I think this is about {}.",
    "Whatever you say, this is about {}.",
    "I don't think {} has anything to do with this.",
    "And here's what reminds me of {}.",
    "This has nothing to do with {}.",
    "{} is completely unrelated to this.",
    "It's clear that {} isn't involved here.",
    "There's no connection between {} and this.",
    "{} doesn't fit into this context at all.",
    "{} is irrelevant in this case.",
    "There's no way {} is part of this.",
    "{} has no bearing on this matter.",
    "This situation doesn't pertain to {}.",
    "{} is not a factor here.",
    "There's no association with {} in this.",
    "{} doesn't come into play here.",
    "This isn't about {} in any way.",
    "{} is not related to this subject.",
    "There's no relevance of {} here.",
    "{} doesn't apply to this scenario.",
    "{} is not connected to this issue.",
    "{} screams from every corner of this.",
    "If {} were a flavor, this would taste like it.",
    "This dances to the rhythm of {}.",
    "This has {} written all over it.",
    "You can smell {} all over this.",
    "This is the anti-{}.",
    "If {} were a book, this would be its intro.",
    "This is what {} looks like in reality.",
    "This makes {} look like a close relative topic.",
]

templates = [f"{t}\n" for t in templates]